# Generated by Django 2.2.14 on 2022-03-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Te', 'Tecnología'), ('Mo', 'Moda'), ('Ar', 'Arte')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field=300, upload_to='', width_field=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'Donación'), ('C', 'Intercambio')], max_length=1),
        ),
    ]
