# Generated by Django 4.0.2 on 2022-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesy_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.TextField(),
        ),
    ]
